### ISSUE TITLE
Makefile bugged!

### ISSUE THREAD

**Issue by szaghi** [szaghi/Lib_VTK_IO#11]
It seems that makefile is bugged (missing Lib_Pack dependency). A kind user (Corentin) already patch the makefile, I will upload soon.

**Comment by szaghi** [comment]
Just upload the patched makefile. Thank you Corentin!

**Comment by corentinroussel** [comment]
You're welcome!

**Comment by szaghi** [comment]
Welcome on Github!

Be careful... Github generates addiction :-)
