### ISSUE TITLE
Tensor data?

### ISSUE THREAD

**Issue by brownto** [szaghi/Lib_VTK_IO#15]
Is there anyway to use VTK_IO to save tensor data to a .vtu file? If not, can you point me to the file format for tensor data in a .vtu file?

Thanks

Tom

**Comment by szaghi** [comment]
Hi @brownto 

Yes, you can save scalar (1 component), vector (3 components), tensor (3x3 components) or n-components field. I have not an example ready, but later in the morning I can try to write one if you can wait. See you later.

**Comment by brownto** [comment]
Thanks.

**Comment by szaghi** [comment]
Hi @brownto 

Unluckly I have not found clear indication into the VTK standard. For the old legacy standard seems that a `tensor` keyword is present, but not for the new XML one. You can try the following:

```fortran
E_IO = VTK_INI_XML(...)
E_IO = VTK_GEO_XML(...)
...
E_IO = VTK_VAR_XML(NC_NN=number_of_your_cells_field, &
  N_COL=9, &
  varname='tensor', &
  var=reshape(tensor,[9,number_of_your_cells_field]))
```

where `tensor` is our tensor array.

Let me know if you have problems.

**Comment by brownto** [comment]
Works perfectly. Thanks.
