### ISSUE TITLE
Makefile is broken

### ISSUE THREAD

**Issue by whophil** [szaghi/Lib_VTK_IO#16]
Makefile is currently broken, complaining about the `IR_precision.f90` module

```make

 Compiler used  gnu => /usr/bin/gfortran
 Source dir     ./src/
  Lib dir        ./static/
  Libray         ./static/Lib_VTK_IO.a
  Shared lib     no
  Debug          no
  F-standard     no
  Optimize       no
  OpenMP         no
  MPI            no
  R16P           (Known R16P switch) Used R16P=no

 Compiling options
 [-cpp -c -J./mod/ ]

 Linking options
 [ ]

make: *** No rule to make target `IR_Precision.f90', needed by `obj/ir_precision.o'.  Stop.

**Comment by szaghi** [comment]
Thank you for pointing out. I am leaving the office. I hope you can wait few days, I am very sorry.

See you soon.

**Comment by szaghi** [comment]
Anyhow the fix should be very quickly and if you cannot wait until I push the fix you can added a patch to your local makefile: simply check the IR_Precision.f90 extension. At sometimes I have changed the case from lower to upper case and then come back without changing the makefile. Try to check this. At a first view it seems that the makefile into the master branch of the github repo is consistent with the src/lib/IR_precision.f90 name. Check your local consistency.

**Comment by whophil** [comment]
Hi @szaghi. I've had some more time to look into this. I'm no Makefile expert, but It looks like it is missing a number of rules. For example, there are no rules for a lot of the dependent modules (for example, any of the `*_back_end.f90` files). Also, the paths for the existing rules are broken, since `$(DSRC)` changed from `./src/` to `./src/lib` at some point. Since there are now quite a few source files, it may be easier to use pattern rules in the Makefile.

Another thing to note, which isn't exactly related to the Makefile but is worth mentioning, is that when the repository is cloned (using `git clone --recursive`), the `src/lib/IR_Precision.f90` is NOT a symlink, but is a text file containing the relative path to the actual `IR_Precision.f90` file. This presents a problem for the compiler.

```
[phil@vm lib]$ cat IR_Precision.f90 
../../external/IR_Precision/src/IR_Precision.f90
```

Let me know what you think about this. I can work with you to make the appropriate changes.

**Comment by szaghi** [comment]
Hi @whophil ,

I am very sorry! Among the other tons of issues (of other works) I completely forget to fix this! Let me few days and I will fix it.

Again I am very sorry!

**Comment by szaghi** [comment]
I have just pushed an updated makefile. It seems to work. I am closing this issue, but feel free to reopen it if the patch does not work as expected.

Thank you for using the library,

my best regards.

**Comment by whophil** [comment]
@szaghi Works great! The only thing to note is that before compiling you need to do one of the following:

1. copy `IR_Precision.f90` from `./external/IR_Precision/src/` into `./src/lib/`, or 
2. create a symbolic link
```
ln -s ./external/IR_Precision/src/IR_Precision.f90 ./src/lib/IR_Precision.f90
```

Thanks again. Looking forward to using this library!

**Comment by szaghi** [comment]
Sorry, the doc is not yet updated, indeed you do not to make links manually, rather, when cloning the repository, do a recursive clone:

```shell
git clone --recursive https://github.com/szaghi/FLAP
```

As a matter of fact, IR_Precision is now a submodule of FLAP project, thus in FLAP it lives into external directory as a git submodule: if you not use recursive, the IR_Precision is not cloned. 

The symlik in to src/lib should be already present (online is present), it is strange that you have to do it manually.

See you soon.
