### ISSUE TITLE
problems with makefile

### ISSUE THREAD

**Issue by vq200** [szaghi/Lib_VTK_IO#18]
Hi Szaghi,
First, thanks a lot for your work!!!
I'm trying to compile your Lib_VTK_IO but I get the following message when running make:

Compiling Lib_Base64.f90
make: *** [obj/lib_base64.o] Error 1
I have no clue what to do. I would appreciate if you could indicate me how to proceed as I'm very interested in using the library.
thanks a lot,
vicent

**Comment by szaghi** [comment]
Dear Vicent,

thank you for interest. 

The Makefile has currently some problems: it should not be up-to-date (the library was under refactoring some months ago, but I had to freeze it for some time). I forget to fix the makefile...

Let me few hours and I try to fix it.

Stay tuned.

P.S. also the documentation is not up-to-date: the Importers are now partially added so the API is changed...

**Comment by szaghi** [comment]
Dear Vicent,

I think that the makefile is ok: I have tested to download and compile the current master branch and all work as expected, see this

```shell
stefano@zaghi(04:34 PM Fri Jan 29)
~/downloads 45 files, 4.1Gb
→ git clone --recursive https://github.com/szaghi/Lib_VTK_IO
Cloning into 'Lib_VTK_IO'...
remote: Counting objects: 6523, done.
remote: Total 6523 (delta 0), reused 0 (delta 0), pack-reused 6523
Receiving objects: 100% (6523/6523), 6.92 MiB | 4.23 MiB/s, done.
Resolving deltas: 100% (4499/4499), done.
Checking connectivity... done.
Submodule 'src/lib/IR_Precision' (https://github.com/szaghi/IR_Precision) registered for path 'external/IR_Precision'
Cloning into 'external/IR_Precision'...
remote: Counting objects: 1062, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 1062 (delta 2), reused 0 (delta 0), pack-reused 1051
Receiving objects: 100% (1062/1062), 1.20 MiB | 775.00 KiB/s, done.
Resolving deltas: 100% (583/583), done.
Checking connectivity... done.
Submodule path 'external/IR_Precision': checked out '97ae156881de860f4e5814e604d814dd4056deef'

stefano@zaghi(04:34 PM Fri Jan 29)
~/downloads 46 files, 4.1Gb
→ cd Lib_VTK_IO/

stefano@zaghi(04:34 PM Fri Jan 29) on master
~/downloads/Lib_VTK_IO 16 files, 260Kb
→ make

 Compiler used  gnu => /usr/bin/gfortran
 Source dir     ./src/lib/ ./src/test/
  Lib dir        ./static/
  Libray         ./static/Lib_VTK_IO.a
  Shared lib     no
  Debug          no
  F-standard     no
  Optimize       no
  OpenMP         no
  MPI            no
  R16P           (Known R16P switch) Used R16P=no

 Compiling options
 [-cpp -c -J./mod/ ]

 Linking options
 [ ]

 Compiling IR_Precision.f90
 Compiling Lib_Pack_Data.f90
 Compiling Lib_Base64.f90
 Compiling Lib_VTK_IO_Back_End.f90
 Compiling Lib_VTK_IO_INI_XML.f90
 Compiling Lib_VTK_IO_FLD_XML.f90
 Compiling Lib_VTK_IO_GEO_XML.f90
 Compiling Lib_VTK_IO_CON_XML.f90
 Compiling Lib_VTK_IO_DAT_VAR_XML.f90
 Compiling Lib_VTK_IO_END_XML.f90
 Compiling Lib_VTK_IO_VTM_XML.f90
 Compiling Lib_VTK_IO_PVTK_XML.f90
 Compiling Lib_VTK_IO_PVD_XML.f90
 Compiling Lib_VTK_IO_INI.f90
 Compiling Lib_VTK_IO_GEO.f90
 Compiling Lib_VTK_IO_CON.f90
 Compiling Lib_VTK_IO_DAT_VAR.f90
 Compiling Lib_VTK_IO_END.f90
 Compiling Lib_VTK_IO.f90
 Linking library Lib_VTK_IO
```

I think that into your Lib_VTK_IO directory root you have not some dependencies. These are download automatically only if you use `git clone --recursive https://github.com/szaghi/Lib_VTK_IO`. Without `--recursive` not all dependencies are downloaded. I have to update the documentation, I am very sorry.

Let me know if this works.

**Comment by szaghi** [comment]
@vq200 Please, note that the API is changed by the one described into the wiki, i.e. currently you have

+ `VTK_INI_XML_WRITE` and `VTK_INI_XML_READ` instead of the single *old* `VTK_INI_XML`
+ `VTK_GEO_XML_WRITE` and `VTK_GEO_XML_READ` instead of the single *old* `VTK_GEO_XML`

**Comment by vq200** [comment]
Thanks a lot Szaghi,
I've repeated now ... and it works perfectly.
vicent

**Comment by szaghi** [comment]
@vq200 You are welcome, I hope to update the library soon. Let me know of any problems you face with, I will try help in case.

See you soon.
